<?php
/**
 * robots.txt, generated so the sitemap it advertises is on the host that served
 * it.
 *
 * .htaccess rewrites /robots.txt here. It was static, and the Sitemap: line
 * named https://slapbabydesigns.co.za even when the same image was answering as
 * slap.yellowarcher.co.za — which lib/config.php says it does, and is the entire
 * reason SLAP_BASE_URL is read from the environment. A crawler on the other
 * hostname was handed a sitemap for a different origin, which is either ignored
 * or treated as a cross-submission; neither is what was meant.
 *
 * Nothing is disallowed, and that is deliberate rather than an omission. See the
 * body below.
 */
declare(strict_types=1);

require __DIR__ . '/lib/bootstrap.php';

header('Content-Type: text/plain; charset=utf-8');
header('Cache-Control: public, max-age=3600');

?>
# <?= SLAP_ORG['name'] ?>. Nothing here is private — the whole site exists to be
# found by someone searching for a memory bear, so nothing is disallowed.
# Per-page control is in lib/pages.php ('robots'), which also drives the <meta>
# tag and the sitemap; a Disallow here would only hide those pages from the
# crawler without removing them from the index.

User-agent: *
Allow: /

# Generated by sitemap.php from the page manifest, served at .xml by .htaccess.
Sitemap: <?= slap_abs('/sitemap.xml') ?>
